

services:

  backend-phutunghd:
    platform: linux/amd64
    container_name: backend-phutunghd
    image: tranhieuphuc12/express-api-phutunghd:latest
    ports:
      - "3001:3001" 
    depends_on:
      - mongodb
    env_file:
      - .env
    restart: always
    networks:
      - nginx_network

  mongodb:
   image: mongo
   volumes:
    - mongo-data:/data/phutungdb
   restart: always
   networks:
    - nginx_network

  frontend:
    platform: linux/amd64
    image: tranhieuphuc12/nextjs-frontend
    container_name: frontend
    restart: always
    expose:
      - 8080
    env_file:
      - .env
    networks:
      - nginx_network

  backend:
    platform: linux/amd64
    image: tranhieuphuc12/express-backend
    container_name: backend
    restart: always
    expose:
      - 3000
    env_file:
      - .env
    networks:
      - nginx_network

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - nginx_network

volumes:
  mongo-data: 

networks:
  nginx_network:
    external: true

